### ISSUE TITLE
Question. Class counter

### ISSUE THREAD

**Issue by tamara-laranga** [mohamedamine99/Object-tracking-and-counting-using-YOLOV8#1]
Hey, good repository really! I need to implement a system to count each class separetly and save the results maybe to a csv. Do you have any idea how to do that?

An example would be; 7 cars, 2 trucks

**Comment by mohamedamine99** [comment]
Hi there,

Thank you for your interest in the repository and your kind words! I appreciate your feedback and I'm glad you find the repository valuable.

Regarding your request to implement a system for counting each class separately and saving the results to a CSV file, I would like to note that the current version of the repository was primarily developed for educational purposes and focuses on the object detection aspect and counting in general rather than class-specific counting.

It's worth mentioning that the YOLOv8 object detection algorithm used in this repository may exhibit some instability, which can lead to confusion between different classes. For example, a car might be detected as a car in one frame, but as a truck in another frame. This is a common challenge with object detection algorithms in general, and **addressing this issue would require adjustments to the detection confidence and modifications to the counting algorithm, such as counting objects that cross a certain line.**

for the csv file part of our question, **I recommend exploring the Python CSV module, which provides easy-to-use methods for reading and writing CSV files**. By modifying the counting algorithm and using the CSV module, you can achieve the desired result of saving the class-specific counts to a CSV file.

If you decide to proceed with this enhancement, I would encourage you to carefully consider the limitations and potential challenges associated with the object detection algorithm's instability. **It may require further experimentation and fine-tuning to achieve accurate class-specific counts.**

If you have any additional questions or need further assistance, please feel free to ask. I'm here to help!

**Comment by mohamedamine99** [comment]
Hi there,

I hope you're doing well. It seems that there hasn't been any response or activity on this issue for a considerable period of time. In order to keep our GitHub repository organized and focused on active issues, I will be closing this issue.

If you still encounter this problem or have additional information to provide, please feel free to reopen this issue or create a new one. I'm here to help!

Thank you for your understanding.
